name: Create a comment on new issue

on:
  issues:
    types: [opened]

jobs:
  comment_witj_action:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on issue
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Thanks for opening this issue!'
          })