name: Create a comment on new issue

on:
  issues:
    types: [opened]

jobs:
 name: Welcome New Issue

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Post Welcome Comment
      uses: actions/github-script@v5 # Pinned version
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          if (context.payload.issue.labels.some(label => label.name === 'bug')) {
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for reporting this bug! Please provide more details so we can investigate further.'
            });
          } else {
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for opening this issue! We appreciate your contribution.'
            });
          }